# Parameters to setup CT simulation.

# dataset
numTrain: 50
numVal: 50

# System configuration
DSD: 1500.0  # Distance Source Detector      (mm)
DSO: 1000.0  # Distance Source Origin        (mm)

# Detector parameters
nDetector: # Number of pixels              (px)
- 512 
- 512 
dDetector: # Size of each pixel            (mm)
- 1.0
- 1.0

# Image parameters
nVoxel: # Number of voxels              (vx)
- 256
- 256
- 128 
dVoxel: # size of each voxel            (mm)      #(128, 256, 256) (1.57774,0,0) (0,0.995861,0) (0,0,1.00797)
- 0.995861
- 1.00797
- 1.57774

# Offsets
offOrigin: # Offset of image from origin   (mm)
- 0 # x direction
- 0 # y direction
- 0 # z direction
offDetector: # Offset of Detector (only in two direction)            (mm)
- 0 # u direction
- 0 # v direction

# Auxiliary
accuracy: 0.5 # Accuracy of FWD proj          (vx/sample)

# Mode
mode: cone # X-ray source mode parallel/cone
filter: null

# Angles
totalAngle: 180.0 # Total angle  (degree)
startAngle: 0.0 # Start angle (degree)
randomAngle: False

# CT
convert: True
rescale_slope: 1.0
rescale_intercept: 0.0
normalize: True

# Noise
noise: 0
