exp:
  expname: head_50
  expdir: ./logs/naf/
  datadir: ./data/head_50.pickle
  image_init: cgls   # fdk / sart / asd_pocs
network:
  net_type: mlp
  num_layers: 4
  hidden_dim: 32
  skips: [2]
  out_dim: 1
  last_activation: sigmoid
  bound: 0.3
encoder:
  encoding: hashgrid
  input_dim: 3
  num_levels: 16
  level_dim: 2
  base_resolution: 16
  log2_hashmap_size: 19
render:
  n_samples: 192    # 第一次在每一条射线上采样点的数量，粗采样
  n_fine: 0         # 第二次采样点，细采样，此处设置成0，表示不细采样
  perturb: True
  raw_noise_std: 0.
  netchunk: 409600  # NeRF模型每一次处理点的个数, batchsize of points
  match_mode: nearest  # mean / nearest / trilinear
train:
  epoch: 3000
  n_batch: 1
  n_rays: 1024
  lrate: 0.001
  lrate_gamma: 0.1
  lrate_step: 500
  resume: False
log:
  i_eval: 250  # Epoch for evaluation
  i_save: 500  # Epoch for saving
